apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-spl-frontend
  labels:
    app: dev-spl-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-spl-frontend
  template:
    metadata:
      labels:
        app: dev-spl-frontend
    spec:
      containers:
        - name: dev-spl-frontend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "3000"
          ports:
            - name: react
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: react
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: react
            initialDelaySeconds: 30
            periodSeconds: 2